// Generated by CoffeeScript 1.9.2
define(['jquery', 'handlebars', 'text!./article.html'], function($, Handlebars, ArticleTemplate) {
  var Article;
  Article = (function() {
    function Article($block) {
      this.$block = $block;
      this.localStorage = window.localStorage;
      this.ArticleTemplate = Handlebars.compile(ArticleTemplate);
      this.init();
    }

    Article.prototype.init = function() {
      return this.getData();
    };

    Article.prototype.getData = function() {
      return $.ajax({
        method: 'get',
        crossDomain: true,
        type: 'POST',
        dataType: "json",
        url: '../json/posts.json',
        success: (function(_this) {
          return function(response) {
            console.log(response);
            if (_this.localStorage.getItem('articles' != null)) {
              return _this.setLocalStorage(response);
            } else {
              return _this.render();
            }
          };
        })(this),
        error: (function(_this) {
          return function(response) {
            return console.log('Error');
          };
        })(this)
      });
    };

    Article.prototype.render = function() {
      var localArticles;
      localArticles = JSON.parse(this.localStorage.getItem('articles'));
      this.$block.html(this.ArticleTemplate({
        conditions: localArticles
      }));
      $('.btn-danger').on('click', (function(_this) {
        return function(e) {
          var deleteId, deleteKey;
          deleteId = $(e.target).data('delete');
          if (deleteId !== '') {
            return _this.removeArticle({
              "id": deleteId,
              "localArticles": localArticles
            });
          } else {
            deleteKey = $(e.target).data('keydelete');
            return _this.removeArticle({
              "id": deleteKey,
              "localArticles": localArticles,
              "deleteByKey": true
            });
          }
        };
      })(this));
      return $('#post-add button[type="submit"]').on('click', (function(_this) {
        return function() {
          var bodyVal, nameVal, tagsVal;
          nameVal = $('#post-add input[name="title"]').val();
          bodyVal = $('#post-add input[name="body"]').val();
          tagsVal = $('#post-add input[name="tags"]').val();
          if ((nameVal != null) && (bodyVal != null) && (tagsVal != null)) {
            return _this.addArticle(nameVal, bodyVal, tagsVal, localArticles);
          }
        };
      })(this));
    };

    Article.prototype.addArticle = function(nameVal, bodyVal, tagsVal, localArticles) {
      var article;
      article = {};
      article.title = nameVal;
      article.body = bodyVal;
      article.tags = tagsVal.split(',');
      localArticles.push(article);
      return this.localStorage.setItem('articles', JSON.stringify(localArticles));
    };

    Article.prototype.removeArticle = function(options) {
      var i;
      console.log(options.id);
      if (options.deleteByKey == null) {
        $('[data-id=' + options.id + ']').fadeOut('500', function() {
          return this.remove();
        });
        i = 0;
        while (i < options.localArticles.length) {
          if (options.localArticles[i].id === options.id) {
            options.localArticles.splice(i, 1);
          }
          i++;
        }
        return this.localStorage.setItem('articles', JSON.stringify(options.localArticles));
      } else {
        $('[data-key=' + options.id + ']').fadeOut('500', function() {
          return this.remove();
        });
        options.localArticles.splice(options.id, 1);
        return this.localStorage.setItem('articles', JSON.stringify(options.localArticles));
      }
    };

    Article.prototype.setLocalStorage = function(response) {
      this.localStorage.setItem('articles', JSON.stringify(response));
      return this.render();
    };

    return Article;

  })();
  return new Article($('#posts'));
});
